import type { BuiltSchema, Panproto } from '@panproto/core'

export type SchemaPair = {
  markdownDocument: BuiltSchema
  editorArticle: BuiltSchema
}

export function buildSchemas(panproto: Panproto): SchemaPair {
  const atproto = panproto.protocol('atproto')

  const markdownDocument = atproto.schema()
    .vertex('md:doc', 'object')
    .vertex('md:title', 'string')
    .vertex('md:description', 'string')
    .vertex('md:tags', 'array')
    .vertex('md:tags:item', 'string')
    .vertex('md:publicationUri', 'string')
    .vertex('md:blocks', 'array')
    .vertex('md:blocks:item', 'union')
    .vertex('md:block:heading', 'object')
    .vertex('md:block:heading:level', 'integer')
    .vertex('md:block:heading:segments', 'array')
    .vertex('md:block:paragraph', 'object')
    .vertex('md:block:paragraph:segments', 'array')
    .vertex('md:block:blockquote', 'object')
    .vertex('md:block:blockquote:segments', 'array')
    .vertex('md:block:code', 'object')
    .vertex('md:block:code:text', 'string')
    .vertex('md:block:code:language', 'string')
    .vertex('md:block:hr', 'object')
    .vertex('md:block:unorderedList', 'object')
    .vertex('md:block:unorderedList:items', 'array')
    .vertex('md:block:orderedList', 'object')
    .vertex('md:block:orderedList:startIndex', 'integer')
    .vertex('md:block:orderedList:items', 'array')
    .vertex('md:block:math', 'object')
    .vertex('md:block:math:tex', 'string')
    .vertex('md:listItem', 'object')
    .vertex('md:listItem:segments', 'array')
    .vertex('md:listItem:checked', 'boolean')
    .vertex('md:listItem:children', 'array')
    .vertex('md:segment', 'object')
    .vertex('md:segment:text', 'string')
    .vertex('md:segment:bold', 'boolean')
    .vertex('md:segment:italic', 'boolean')
    .vertex('md:segment:code', 'boolean')
    .vertex('md:segment:strikethrough', 'boolean')
    .vertex('md:segment:linkUri', 'string')
    .edge('md:doc', 'md:title', 'prop', { name: 'title' })
    .edge('md:doc', 'md:description', 'prop', { name: 'description' })
    .edge('md:doc', 'md:tags', 'prop', { name: 'tags' })
    .edge('md:tags', 'md:tags:item', 'items')
    .edge('md:doc', 'md:publicationUri', 'prop', { name: 'publicationUri' })
    .edge('md:doc', 'md:blocks', 'prop', { name: 'blocks' })
    .edge('md:blocks', 'md:blocks:item', 'items')
    .edge('md:blocks:item', 'md:block:heading', 'union_variant', { name: 'heading' })
    .edge('md:blocks:item', 'md:block:paragraph', 'union_variant', { name: 'paragraph' })
    .edge('md:blocks:item', 'md:block:blockquote', 'union_variant', { name: 'blockquote' })
    .edge('md:blocks:item', 'md:block:code', 'union_variant', { name: 'code' })
    .edge('md:blocks:item', 'md:block:hr', 'union_variant', { name: 'horizontalRule' })
    .edge('md:blocks:item', 'md:block:unorderedList', 'union_variant', { name: 'unorderedList' })
    .edge('md:blocks:item', 'md:block:orderedList', 'union_variant', { name: 'orderedList' })
    .edge('md:blocks:item', 'md:block:math', 'union_variant', { name: 'math' })
    .edge('md:block:heading', 'md:block:heading:level', 'prop', { name: 'level' })
    .edge('md:block:heading', 'md:block:heading:segments', 'prop', { name: 'segments' })
    .edge('md:block:heading:segments', 'md:segment', 'items')
    .edge('md:block:paragraph', 'md:block:paragraph:segments', 'prop', { name: 'segments' })
    .edge('md:block:paragraph:segments', 'md:segment', 'items')
    .edge('md:block:blockquote', 'md:block:blockquote:segments', 'prop', { name: 'segments' })
    .edge('md:block:blockquote:segments', 'md:segment', 'items')
    .edge('md:block:code', 'md:block:code:text', 'prop', { name: 'text' })
    .edge('md:block:code', 'md:block:code:language', 'prop', { name: 'language' })
    .edge('md:block:unorderedList', 'md:block:unorderedList:items', 'prop', { name: 'items' })
    .edge('md:block:unorderedList:items', 'md:listItem', 'items')
    .edge('md:block:orderedList', 'md:block:orderedList:startIndex', 'prop', { name: 'startIndex' })
    .edge('md:block:orderedList', 'md:block:orderedList:items', 'prop', { name: 'items' })
    .edge('md:block:orderedList:items', 'md:listItem', 'items')
    .edge('md:block:math', 'md:block:math:tex', 'prop', { name: 'tex' })
    .edge('md:listItem', 'md:listItem:segments', 'prop', { name: 'segments' })
    .edge('md:listItem:segments', 'md:segment', 'items')
    .edge('md:listItem', 'md:listItem:checked', 'prop', { name: 'checked' })
    .edge('md:listItem', 'md:listItem:children', 'prop', { name: 'children' })
    .edge('md:listItem:children', 'md:listItem', 'items')
    .edge('md:segment', 'md:segment:text', 'prop', { name: 'text' })
    .edge('md:segment', 'md:segment:bold', 'prop', { name: 'bold' })
    .edge('md:segment', 'md:segment:italic', 'prop', { name: 'italic' })
    .edge('md:segment', 'md:segment:code', 'prop', { name: 'code' })
    .edge('md:segment', 'md:segment:strikethrough', 'prop', { name: 'strikethrough' })
    .edge('md:segment', 'md:segment:linkUri', 'prop', { name: 'linkUri' })
    .build()

  const editorArticle = atproto.schema()
    .vertex('ed:article', 'object')
    .vertex('ed:title', 'string')
    .vertex('ed:description', 'string')
    .vertex('ed:tags', 'array')
    .vertex('ed:tags:item', 'string')
    .vertex('ed:site', 'string')
    .vertex('ed:publishedAt', 'string')
    .vertex('ed:updatedAt', 'string')
    .vertex('ed:blocks', 'array')
    .vertex('ed:blocks:item', 'union')
    .vertex('ed:block:header', 'object')
    .vertex('ed:block:header:level', 'integer')
    .vertex('ed:block:header:segments', 'array')
    .vertex('ed:block:text', 'object')
    .vertex('ed:block:text:segments', 'array')
    .vertex('ed:block:blockquote', 'object')
    .vertex('ed:block:blockquote:segments', 'array')
    .vertex('ed:block:code', 'object')
    .vertex('ed:block:code:text', 'string')
    .vertex('ed:block:code:language', 'string')
    .vertex('ed:block:hr', 'object')
    .vertex('ed:block:unorderedList', 'object')
    .vertex('ed:block:unorderedList:items', 'array')
    .vertex('ed:block:orderedList', 'object')
    .vertex('ed:block:orderedList:startIndex', 'integer')
    .vertex('ed:block:orderedList:items', 'array')
    .vertex('ed:block:math', 'object')
    .vertex('ed:block:math:tex', 'string')
    .vertex('ed:listItem', 'object')
    .vertex('ed:listItem:segments', 'array')
    .vertex('ed:listItem:checked', 'boolean')
    .vertex('ed:listItem:children', 'array')
    .vertex('ed:segment', 'object')
    .vertex('ed:segment:text', 'string')
    .vertex('ed:segment:bold', 'boolean')
    .vertex('ed:segment:italic', 'boolean')
    .vertex('ed:segment:code', 'boolean')
    .vertex('ed:segment:strikethrough', 'boolean')
    .vertex('ed:segment:linkUri', 'string')
    .edge('ed:article', 'ed:title', 'prop', { name: 'title' })
    .edge('ed:article', 'ed:description', 'prop', { name: 'description' })
    .edge('ed:article', 'ed:tags', 'prop', { name: 'tags' })
    .edge('ed:tags', 'ed:tags:item', 'items')
    .edge('ed:article', 'ed:site', 'prop', { name: 'site' })
    .edge('ed:article', 'ed:publishedAt', 'prop', { name: 'publishedAt' })
    .edge('ed:article', 'ed:updatedAt', 'prop', { name: 'updatedAt' })
    .edge('ed:article', 'ed:blocks', 'prop', { name: 'blocks' })
    .edge('ed:blocks', 'ed:blocks:item', 'items')
    .edge('ed:blocks:item', 'ed:block:header', 'union_variant', { name: 'header' })
    .edge('ed:blocks:item', 'ed:block:text', 'union_variant', { name: 'text' })
    .edge('ed:blocks:item', 'ed:block:blockquote', 'union_variant', { name: 'blockquote' })
    .edge('ed:blocks:item', 'ed:block:code', 'union_variant', { name: 'code' })
    .edge('ed:blocks:item', 'ed:block:hr', 'union_variant', { name: 'horizontalRule' })
    .edge('ed:blocks:item', 'ed:block:unorderedList', 'union_variant', { name: 'unorderedList' })
    .edge('ed:blocks:item', 'ed:block:orderedList', 'union_variant', { name: 'orderedList' })
    .edge('ed:blocks:item', 'ed:block:math', 'union_variant', { name: 'math' })
    .edge('ed:block:header', 'ed:block:header:level', 'prop', { name: 'level' })
    .edge('ed:block:header', 'ed:block:header:segments', 'prop', { name: 'segments' })
    .edge('ed:block:header:segments', 'ed:segment', 'items')
    .edge('ed:block:text', 'ed:block:text:segments', 'prop', { name: 'segments' })
    .edge('ed:block:text:segments', 'ed:segment', 'items')
    .edge('ed:block:blockquote', 'ed:block:blockquote:segments', 'prop', { name: 'segments' })
    .edge('ed:block:blockquote:segments', 'ed:segment', 'items')
    .edge('ed:block:code', 'ed:block:code:text', 'prop', { name: 'text' })
    .edge('ed:block:code', 'ed:block:code:language', 'prop', { name: 'language' })
    .edge('ed:block:unorderedList', 'ed:block:unorderedList:items', 'prop', { name: 'items' })
    .edge('ed:block:unorderedList:items', 'ed:listItem', 'items')
    .edge('ed:block:orderedList', 'ed:block:orderedList:startIndex', 'prop', { name: 'startIndex' })
    .edge('ed:block:orderedList', 'ed:block:orderedList:items', 'prop', { name: 'items' })
    .edge('ed:block:orderedList:items', 'ed:listItem', 'items')
    .edge('ed:block:math', 'ed:block:math:tex', 'prop', { name: 'tex' })
    .edge('ed:listItem', 'ed:listItem:segments', 'prop', { name: 'segments' })
    .edge('ed:listItem:segments', 'ed:segment', 'items')
    .edge('ed:listItem', 'ed:listItem:checked', 'prop', { name: 'checked' })
    .edge('ed:listItem', 'ed:listItem:children', 'prop', { name: 'children' })
    .edge('ed:listItem:children', 'ed:listItem', 'items')
    .edge('ed:segment', 'ed:segment:text', 'prop', { name: 'text' })
    .edge('ed:segment', 'ed:segment:bold', 'prop', { name: 'bold' })
    .edge('ed:segment', 'ed:segment:italic', 'prop', { name: 'italic' })
    .edge('ed:segment', 'ed:segment:code', 'prop', { name: 'code' })
    .edge('ed:segment', 'ed:segment:strikethrough', 'prop', { name: 'strikethrough' })
    .edge('ed:segment', 'ed:segment:linkUri', 'prop', { name: 'linkUri' })
    .build()

  return { markdownDocument, editorArticle }
}
