import type { BuiltSchema, Panproto } from '@panproto/core'

export type SchemaTriple = {
  markdownDocument: BuiltSchema
  editorArticle: BuiltSchema
  siteStandardDocument: BuiltSchema
}

export function buildSchemas(panproto: Panproto): SchemaTriple {
  const atproto = panproto.protocol('atproto')

  const markdownDocument = atproto.schema()
    .vertex('md:doc', 'object')
    .vertex('md:title', 'string')
    .vertex('md:description', 'string')
    .vertex('md:tags', 'array')
    .vertex('md:tags:item', 'string')
    .vertex('md:publicationUri', 'string')
    .vertex('md:blocks', 'array')
    .vertex('md:blocks:item', 'union')
    .vertex('md:block:heading', 'object')
    .vertex('md:block:heading:level', 'integer')
    .vertex('md:block:heading:segments', 'array')
    .vertex('md:block:paragraph', 'object')
    .vertex('md:block:paragraph:segments', 'array')
    .vertex('md:block:blockquote', 'object')
    .vertex('md:block:blockquote:segments', 'array')
    .vertex('md:block:code', 'object')
    .vertex('md:block:code:text', 'string')
    .vertex('md:block:code:language', 'string')
    .vertex('md:block:hr', 'object')
    .vertex('md:block:unorderedList', 'object')
    .vertex('md:block:unorderedList:items', 'array')
    .vertex('md:block:orderedList', 'object')
    .vertex('md:block:orderedList:startIndex', 'integer')
    .vertex('md:block:orderedList:items', 'array')
    .vertex('md:block:math', 'object')
    .vertex('md:block:math:tex', 'string')
    .vertex('md:listItem', 'object')
    .vertex('md:listItem:segments', 'array')
    .vertex('md:listItem:checked', 'boolean')
    .vertex('md:listItem:children', 'array')
    .vertex('md:segment', 'object')
    .vertex('md:segment:text', 'string')
    .vertex('md:segment:bold', 'boolean')
    .vertex('md:segment:italic', 'boolean')
    .vertex('md:segment:code', 'boolean')
    .vertex('md:segment:strikethrough', 'boolean')
    .vertex('md:segment:linkUri', 'string')
    .edge('md:doc', 'md:title', 'prop', { name: 'title' })
    .edge('md:doc', 'md:description', 'prop', { name: 'description' })
    .edge('md:doc', 'md:tags', 'prop', { name: 'tags' })
    .edge('md:tags', 'md:tags:item', 'items')
    .edge('md:doc', 'md:publicationUri', 'prop', { name: 'publicationUri' })
    .edge('md:doc', 'md:blocks', 'prop', { name: 'blocks' })
    .edge('md:blocks', 'md:blocks:item', 'items')
    .edge('md:blocks:item', 'md:block:heading', 'union_variant', { name: 'heading' })
    .edge('md:blocks:item', 'md:block:paragraph', 'union_variant', { name: 'paragraph' })
    .edge('md:blocks:item', 'md:block:blockquote', 'union_variant', { name: 'blockquote' })
    .edge('md:blocks:item', 'md:block:code', 'union_variant', { name: 'code' })
    .edge('md:blocks:item', 'md:block:hr', 'union_variant', { name: 'horizontalRule' })
    .edge('md:blocks:item', 'md:block:unorderedList', 'union_variant', { name: 'unorderedList' })
    .edge('md:blocks:item', 'md:block:orderedList', 'union_variant', { name: 'orderedList' })
    .edge('md:blocks:item', 'md:block:math', 'union_variant', { name: 'math' })
    .edge('md:block:heading', 'md:block:heading:level', 'prop', { name: 'level' })
    .edge('md:block:heading', 'md:block:heading:segments', 'prop', { name: 'segments' })
    .edge('md:block:heading:segments', 'md:segment', 'items')
    .edge('md:block:paragraph', 'md:block:paragraph:segments', 'prop', { name: 'segments' })
    .edge('md:block:paragraph:segments', 'md:segment', 'items')
    .edge('md:block:blockquote', 'md:block:blockquote:segments', 'prop', { name: 'segments' })
    .edge('md:block:blockquote:segments', 'md:segment', 'items')
    .edge('md:block:code', 'md:block:code:text', 'prop', { name: 'text' })
    .edge('md:block:code', 'md:block:code:language', 'prop', { name: 'language' })
    .edge('md:block:unorderedList', 'md:block:unorderedList:items', 'prop', { name: 'items' })
    .edge('md:block:unorderedList:items', 'md:listItem', 'items')
    .edge('md:block:orderedList', 'md:block:orderedList:startIndex', 'prop', { name: 'startIndex' })
    .edge('md:block:orderedList', 'md:block:orderedList:items', 'prop', { name: 'items' })
    .edge('md:block:orderedList:items', 'md:listItem', 'items')
    .edge('md:block:math', 'md:block:math:tex', 'prop', { name: 'tex' })
    .edge('md:listItem', 'md:listItem:segments', 'prop', { name: 'segments' })
    .edge('md:listItem:segments', 'md:segment', 'items')
    .edge('md:listItem', 'md:listItem:checked', 'prop', { name: 'checked' })
    .edge('md:listItem', 'md:listItem:children', 'prop', { name: 'children' })
    .edge('md:listItem:children', 'md:listItem', 'items')
    .edge('md:segment', 'md:segment:text', 'prop', { name: 'text' })
    .edge('md:segment', 'md:segment:bold', 'prop', { name: 'bold' })
    .edge('md:segment', 'md:segment:italic', 'prop', { name: 'italic' })
    .edge('md:segment', 'md:segment:code', 'prop', { name: 'code' })
    .edge('md:segment', 'md:segment:strikethrough', 'prop', { name: 'strikethrough' })
    .edge('md:segment', 'md:segment:linkUri', 'prop', { name: 'linkUri' })
    .build()

  const editorArticle = atproto.schema()
    .vertex('ed:article', 'object')
    .vertex('ed:title', 'string')
    .vertex('ed:description', 'string')
    .vertex('ed:tags', 'array')
    .vertex('ed:tags:item', 'string')
    .vertex('ed:site', 'string')
    .vertex('ed:publishedAt', 'string')
    .vertex('ed:updatedAt', 'string')
    .vertex('ed:blocks', 'array')
    .vertex('ed:blocks:item', 'union')
    .vertex('ed:block:header', 'object')
    .vertex('ed:block:header:level', 'integer')
    .vertex('ed:block:header:segments', 'array')
    .vertex('ed:block:text', 'object')
    .vertex('ed:block:text:segments', 'array')
    .vertex('ed:block:blockquote', 'object')
    .vertex('ed:block:blockquote:segments', 'array')
    .vertex('ed:block:code', 'object')
    .vertex('ed:block:code:text', 'string')
    .vertex('ed:block:code:language', 'string')
    .vertex('ed:block:hr', 'object')
    .vertex('ed:block:unorderedList', 'object')
    .vertex('ed:block:unorderedList:items', 'array')
    .vertex('ed:block:orderedList', 'object')
    .vertex('ed:block:orderedList:startIndex', 'integer')
    .vertex('ed:block:orderedList:items', 'array')
    .vertex('ed:block:math', 'object')
    .vertex('ed:block:math:tex', 'string')
    .vertex('ed:listItem', 'object')
    .vertex('ed:listItem:segments', 'array')
    .vertex('ed:listItem:checked', 'boolean')
    .vertex('ed:listItem:children', 'array')
    .vertex('ed:segment', 'object')
    .vertex('ed:segment:text', 'string')
    .vertex('ed:segment:bold', 'boolean')
    .vertex('ed:segment:italic', 'boolean')
    .vertex('ed:segment:code', 'boolean')
    .vertex('ed:segment:strikethrough', 'boolean')
    .vertex('ed:segment:linkUri', 'string')
    .edge('ed:article', 'ed:title', 'prop', { name: 'title' })
    .edge('ed:article', 'ed:description', 'prop', { name: 'description' })
    .edge('ed:article', 'ed:tags', 'prop', { name: 'tags' })
    .edge('ed:tags', 'ed:tags:item', 'items')
    .edge('ed:article', 'ed:site', 'prop', { name: 'site' })
    .edge('ed:article', 'ed:publishedAt', 'prop', { name: 'publishedAt' })
    .edge('ed:article', 'ed:updatedAt', 'prop', { name: 'updatedAt' })
    .edge('ed:article', 'ed:blocks', 'prop', { name: 'blocks' })
    .edge('ed:blocks', 'ed:blocks:item', 'items')
    .edge('ed:blocks:item', 'ed:block:header', 'union_variant', { name: 'header' })
    .edge('ed:blocks:item', 'ed:block:text', 'union_variant', { name: 'text' })
    .edge('ed:blocks:item', 'ed:block:blockquote', 'union_variant', { name: 'blockquote' })
    .edge('ed:blocks:item', 'ed:block:code', 'union_variant', { name: 'code' })
    .edge('ed:blocks:item', 'ed:block:hr', 'union_variant', { name: 'horizontalRule' })
    .edge('ed:blocks:item', 'ed:block:unorderedList', 'union_variant', { name: 'unorderedList' })
    .edge('ed:blocks:item', 'ed:block:orderedList', 'union_variant', { name: 'orderedList' })
    .edge('ed:blocks:item', 'ed:block:math', 'union_variant', { name: 'math' })
    .edge('ed:block:header', 'ed:block:header:level', 'prop', { name: 'level' })
    .edge('ed:block:header', 'ed:block:header:segments', 'prop', { name: 'segments' })
    .edge('ed:block:header:segments', 'ed:segment', 'items')
    .edge('ed:block:text', 'ed:block:text:segments', 'prop', { name: 'segments' })
    .edge('ed:block:text:segments', 'ed:segment', 'items')
    .edge('ed:block:blockquote', 'ed:block:blockquote:segments', 'prop', { name: 'segments' })
    .edge('ed:block:blockquote:segments', 'ed:segment', 'items')
    .edge('ed:block:code', 'ed:block:code:text', 'prop', { name: 'text' })
    .edge('ed:block:code', 'ed:block:code:language', 'prop', { name: 'language' })
    .edge('ed:block:unorderedList', 'ed:block:unorderedList:items', 'prop', { name: 'items' })
    .edge('ed:block:unorderedList:items', 'ed:listItem', 'items')
    .edge('ed:block:orderedList', 'ed:block:orderedList:startIndex', 'prop', { name: 'startIndex' })
    .edge('ed:block:orderedList', 'ed:block:orderedList:items', 'prop', { name: 'items' })
    .edge('ed:block:orderedList:items', 'ed:listItem', 'items')
    .edge('ed:block:math', 'ed:block:math:tex', 'prop', { name: 'tex' })
    .edge('ed:listItem', 'ed:listItem:segments', 'prop', { name: 'segments' })
    .edge('ed:listItem:segments', 'ed:segment', 'items')
    .edge('ed:listItem', 'ed:listItem:checked', 'prop', { name: 'checked' })
    .edge('ed:listItem', 'ed:listItem:children', 'prop', { name: 'children' })
    .edge('ed:listItem:children', 'ed:listItem', 'items')
    .edge('ed:segment', 'ed:segment:text', 'prop', { name: 'text' })
    .edge('ed:segment', 'ed:segment:bold', 'prop', { name: 'bold' })
    .edge('ed:segment', 'ed:segment:italic', 'prop', { name: 'italic' })
    .edge('ed:segment', 'ed:segment:code', 'prop', { name: 'code' })
    .edge('ed:segment', 'ed:segment:strikethrough', 'prop', { name: 'strikethrough' })
    .edge('ed:segment', 'ed:segment:linkUri', 'prop', { name: 'linkUri' })
    .build()

  const siteStandardDocument = atproto.schema()
    .vertex('lx:doc', 'object')
    .vertex('lx:doc:$type', 'string')
    .vertex('lx:doc:site', 'string')
    .vertex('lx:doc:title', 'string')
    .vertex('lx:doc:publishedAt', 'string')
    .vertex('lx:doc:path', 'string')
    .vertex('lx:doc:description', 'string')
    .vertex('lx:docTags', 'array')
    .vertex('lx:docTags:item', 'string')
    .vertex('lx:doc:updatedAt', 'string')
    .vertex('lx:contentItem', 'union')
    .vertex('lx:contentObj', 'object')
    .vertex('lx:contentObj:$type', 'string')
    .vertex('lx:contentPages', 'array')
    .vertex('lx:pageItem', 'union')
    .vertex('lx:page:linearDoc', 'object')
    .vertex('lx:page:linearDoc:$type', 'string')
    .vertex('lx:page:linearDoc:id', 'string')
    .vertex('lx:page:linearDoc:blocks', 'array')
    .vertex('lx:blockWrapper', 'object')
    .vertex('lx:blockWrapper:$type', 'string')
    .vertex('lx:blockWrapperBlock', 'union')
    .vertex('lx:block:text', 'object')
    .vertex('lx:block:text:$type', 'string')
    .vertex('lx:block:text:plaintext', 'string')
    .vertex('lx:block:text:facets', 'array')
    .vertex('lx:block:header', 'object')
    .vertex('lx:block:header:$type', 'string')
    .vertex('lx:block:header:level', 'integer')
    .vertex('lx:block:header:plaintext', 'string')
    .vertex('lx:block:header:facets', 'array')
    .vertex('lx:block:blockquote', 'object')
    .vertex('lx:block:blockquote:$type', 'string')
    .vertex('lx:block:blockquote:plaintext', 'string')
    .vertex('lx:block:blockquote:facets', 'array')
    .vertex('lx:block:code', 'object')
    .vertex('lx:block:code:$type', 'string')
    .vertex('lx:block:code:plaintext', 'string')
    .vertex('lx:block:code:language', 'string')
    .vertex('lx:block:hr', 'object')
    .vertex('lx:block:hr:$type', 'string')
    .vertex('lx:block:unorderedList', 'object')
    .vertex('lx:block:unorderedList:$type', 'string')
    .vertex('lx:block:unorderedList:children', 'array')
    .vertex('lx:block:orderedList', 'object')
    .vertex('lx:block:orderedList:$type', 'string')
    .vertex('lx:block:orderedList:startIndex', 'integer')
    .vertex('lx:block:orderedList:children', 'array')
    .vertex('lx:block:math', 'object')
    .vertex('lx:block:math:$type', 'string')
    .vertex('lx:block:math:tex', 'string')
    .vertex('lx:facet', 'object')
    .vertex('lx:facet:$type', 'string')
    .vertex('lx:byteSlice', 'object')
    .vertex('lx:byteSlice:byteStart', 'integer')
    .vertex('lx:byteSlice:byteEnd', 'integer')
    .vertex('lx:facetFeatures', 'array')
    .vertex('lx:featureItem', 'union')
    .vertex('lx:feature:link', 'object')
    .vertex('lx:feature:link:$type', 'string')
    .vertex('lx:feature:link:uri', 'string')
    .vertex('lx:feature:bold', 'object')
    .vertex('lx:feature:bold:$type', 'string')
    .vertex('lx:feature:italic', 'object')
    .vertex('lx:feature:italic:$type', 'string')
    .vertex('lx:feature:code', 'object')
    .vertex('lx:feature:code:$type', 'string')
    .vertex('lx:feature:strikethrough', 'object')
    .vertex('lx:feature:strikethrough:$type', 'string')
    .vertex('lx:unorderedListItem', 'object')
    .vertex('lx:unorderedListItem:$type', 'string')
    .vertex('lx:unorderedListItemContent', 'union')
    .vertex('lx:unorderedListItem:checked', 'boolean')
    .vertex('lx:unorderedListItem:children', 'array')
    .vertex('lx:orderedListItem', 'object')
    .vertex('lx:orderedListItem:$type', 'string')
    .vertex('lx:orderedListItemContent', 'union')
    .vertex('lx:orderedListItem:checked', 'boolean')
    .vertex('lx:orderedListItem:children', 'array')
    .edge('lx:doc', 'lx:doc:$type', 'prop', { name: '$type' })
    .edge('lx:doc', 'lx:doc:site', 'prop', { name: 'site' })
    .edge('lx:doc', 'lx:doc:title', 'prop', { name: 'title' })
    .edge('lx:doc', 'lx:doc:publishedAt', 'prop', { name: 'publishedAt' })
    .edge('lx:doc', 'lx:doc:path', 'prop', { name: 'path' })
    .edge('lx:doc', 'lx:doc:description', 'prop', { name: 'description' })
    .edge('lx:doc', 'lx:docTags', 'prop', { name: 'tags' })
    .edge('lx:docTags', 'lx:docTags:item', 'items')
    .edge('lx:doc', 'lx:doc:updatedAt', 'prop', { name: 'updatedAt' })
    .edge('lx:doc', 'lx:contentItem', 'prop', { name: 'content' })
    .edge('lx:contentItem', 'lx:contentObj', 'union_variant', { name: 'pub.leaflet.content' })
    .edge('lx:contentObj', 'lx:contentObj:$type', 'prop', { name: '$type' })
    .edge('lx:contentObj', 'lx:contentPages', 'prop', { name: 'pages' })
    .edge('lx:contentPages', 'lx:pageItem', 'items')
    .edge('lx:pageItem', 'lx:page:linearDoc', 'union_variant', { name: 'pub.leaflet.pages.linearDocument' })
    .edge('lx:page:linearDoc', 'lx:page:linearDoc:$type', 'prop', { name: '$type' })
    .edge('lx:page:linearDoc', 'lx:page:linearDoc:id', 'prop', { name: 'id' })
    .edge('lx:page:linearDoc', 'lx:page:linearDoc:blocks', 'prop', { name: 'blocks' })
    .edge('lx:page:linearDoc:blocks', 'lx:blockWrapper', 'items')
    .edge('lx:blockWrapper', 'lx:blockWrapper:$type', 'prop', { name: '$type' })
    .edge('lx:blockWrapper', 'lx:blockWrapperBlock', 'prop', { name: 'block' })
    .edge('lx:blockWrapperBlock', 'lx:block:text', 'union_variant', { name: 'pub.leaflet.blocks.text' })
    .edge('lx:blockWrapperBlock', 'lx:block:header', 'union_variant', { name: 'pub.leaflet.blocks.header' })
    .edge('lx:blockWrapperBlock', 'lx:block:blockquote', 'union_variant', { name: 'pub.leaflet.blocks.blockquote' })
    .edge('lx:blockWrapperBlock', 'lx:block:code', 'union_variant', { name: 'pub.leaflet.blocks.code' })
    .edge('lx:blockWrapperBlock', 'lx:block:hr', 'union_variant', { name: 'pub.leaflet.blocks.horizontalRule' })
    .edge('lx:blockWrapperBlock', 'lx:block:unorderedList', 'union_variant', { name: 'pub.leaflet.blocks.unorderedList' })
    .edge('lx:blockWrapperBlock', 'lx:block:orderedList', 'union_variant', { name: 'pub.leaflet.blocks.orderedList' })
    .edge('lx:blockWrapperBlock', 'lx:block:math', 'union_variant', { name: 'pub.leaflet.blocks.math' })
    .edge('lx:block:text', 'lx:block:text:$type', 'prop', { name: '$type' })
    .edge('lx:block:text', 'lx:block:text:plaintext', 'prop', { name: 'plaintext' })
    .edge('lx:block:text', 'lx:block:text:facets', 'prop', { name: 'facets' })
    .edge('lx:block:text:facets', 'lx:facet', 'items')
    .edge('lx:block:header', 'lx:block:header:$type', 'prop', { name: '$type' })
    .edge('lx:block:header', 'lx:block:header:level', 'prop', { name: 'level' })
    .edge('lx:block:header', 'lx:block:header:plaintext', 'prop', { name: 'plaintext' })
    .edge('lx:block:header', 'lx:block:header:facets', 'prop', { name: 'facets' })
    .edge('lx:block:header:facets', 'lx:facet', 'items')
    .edge('lx:block:blockquote', 'lx:block:blockquote:$type', 'prop', { name: '$type' })
    .edge('lx:block:blockquote', 'lx:block:blockquote:plaintext', 'prop', { name: 'plaintext' })
    .edge('lx:block:blockquote', 'lx:block:blockquote:facets', 'prop', { name: 'facets' })
    .edge('lx:block:blockquote:facets', 'lx:facet', 'items')
    .edge('lx:block:code', 'lx:block:code:$type', 'prop', { name: '$type' })
    .edge('lx:block:code', 'lx:block:code:plaintext', 'prop', { name: 'plaintext' })
    .edge('lx:block:code', 'lx:block:code:language', 'prop', { name: 'language' })
    .edge('lx:block:hr', 'lx:block:hr:$type', 'prop', { name: '$type' })
    .edge('lx:block:unorderedList', 'lx:block:unorderedList:$type', 'prop', { name: '$type' })
    .edge('lx:block:unorderedList', 'lx:block:unorderedList:children', 'prop', { name: 'children' })
    .edge('lx:block:unorderedList:children', 'lx:unorderedListItem', 'items')
    .edge('lx:block:orderedList', 'lx:block:orderedList:$type', 'prop', { name: '$type' })
    .edge('lx:block:orderedList', 'lx:block:orderedList:startIndex', 'prop', { name: 'startIndex' })
    .edge('lx:block:orderedList', 'lx:block:orderedList:children', 'prop', { name: 'children' })
    .edge('lx:block:orderedList:children', 'lx:orderedListItem', 'items')
    .edge('lx:block:math', 'lx:block:math:$type', 'prop', { name: '$type' })
    .edge('lx:block:math', 'lx:block:math:tex', 'prop', { name: 'tex' })
    .edge('lx:facet', 'lx:facet:$type', 'prop', { name: '$type' })
    .edge('lx:facet', 'lx:byteSlice', 'prop', { name: 'index' })
    .edge('lx:byteSlice', 'lx:byteSlice:byteStart', 'prop', { name: 'byteStart' })
    .edge('lx:byteSlice', 'lx:byteSlice:byteEnd', 'prop', { name: 'byteEnd' })
    .edge('lx:facet', 'lx:facetFeatures', 'prop', { name: 'features' })
    .edge('lx:facetFeatures', 'lx:featureItem', 'items')
    .edge('lx:featureItem', 'lx:feature:link', 'union_variant', { name: 'pub.leaflet.richtext.facet#link' })
    .edge('lx:featureItem', 'lx:feature:bold', 'union_variant', { name: 'pub.leaflet.richtext.facet#bold' })
    .edge('lx:featureItem', 'lx:feature:italic', 'union_variant', { name: 'pub.leaflet.richtext.facet#italic' })
    .edge('lx:featureItem', 'lx:feature:code', 'union_variant', { name: 'pub.leaflet.richtext.facet#code' })
    .edge('lx:featureItem', 'lx:feature:strikethrough', 'union_variant', { name: 'pub.leaflet.richtext.facet#strikethrough' })
    .edge('lx:feature:link', 'lx:feature:link:$type', 'prop', { name: '$type' })
    .edge('lx:feature:link', 'lx:feature:link:uri', 'prop', { name: 'uri' })
    .edge('lx:feature:bold', 'lx:feature:bold:$type', 'prop', { name: '$type' })
    .edge('lx:feature:italic', 'lx:feature:italic:$type', 'prop', { name: '$type' })
    .edge('lx:feature:code', 'lx:feature:code:$type', 'prop', { name: '$type' })
    .edge('lx:feature:strikethrough', 'lx:feature:strikethrough:$type', 'prop', { name: '$type' })
    .edge('lx:unorderedListItem', 'lx:unorderedListItem:$type', 'prop', { name: '$type' })
    .edge('lx:unorderedListItem', 'lx:unorderedListItemContent', 'prop', { name: 'content' })
    .edge('lx:unorderedListItemContent', 'lx:block:text', 'union_variant', { name: 'pub.leaflet.blocks.text' })
    .edge('lx:unorderedListItemContent', 'lx:block:header', 'union_variant', { name: 'pub.leaflet.blocks.header' })
    .edge('lx:unorderedListItem', 'lx:unorderedListItem:checked', 'prop', { name: 'checked' })
    .edge('lx:unorderedListItem', 'lx:unorderedListItem:children', 'prop', { name: 'children' })
    .edge('lx:unorderedListItem:children', 'lx:unorderedListItem', 'items')
    .edge('lx:orderedListItem', 'lx:orderedListItem:$type', 'prop', { name: '$type' })
    .edge('lx:orderedListItem', 'lx:orderedListItemContent', 'prop', { name: 'content' })
    .edge('lx:orderedListItemContent', 'lx:block:text', 'union_variant', { name: 'pub.leaflet.blocks.text' })
    .edge('lx:orderedListItemContent', 'lx:block:header', 'union_variant', { name: 'pub.leaflet.blocks.header' })
    .edge('lx:orderedListItem', 'lx:orderedListItem:checked', 'prop', { name: 'checked' })
    .edge('lx:orderedListItem', 'lx:orderedListItem:children', 'prop', { name: 'children' })
    .edge('lx:orderedListItem:children', 'lx:orderedListItem', 'items')
    .build()

  return { markdownDocument, editorArticle, siteStandardDocument }
}
